site_name: Moje projekty
site_author: Maciej Sobczak
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: maciejATcosphere/ds_ai_portfolio
repo_url: https://github.com/maciejATcosphere/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: yellow

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Titanic": titanic/index.md
- Poprzednie projekty:
  - "Iris": iris/index.md
